Add Christmas challenge
RoboCupJuniorTC/soccer-2022 pull request #4
Opened 2022-10-10 19:49 UTC by Adman

Signed-off-by: Adrian Matejov <ado.matejov@gmail.com>

2022-10-12 20:34 UTC, mrshu requested changes
Thanks for adding this @Adman!

I left a couple of comments here and there but nothing especially major :slightly_smiling_face:

2022-10-12 20:34 UTC, mrshu commented on docs/end-of-2022-challenge.md
> +noticed that many of the robots use omiwheled way of moving on the field,
@Adman do you think it might make sense to say "omnidirectional wheels" (wheels that can move along two axes) here?

2022-10-12 20:34 UTC, mrshu commented on docs/end-of-2022-challenge.md
> +we would like to introduce omniwheeled robots in SoccerSim. Your task is to design
```suggestion
we would like to introduce omniwheeled robots in SoccerSim as well. Your task is to design
```

2022-10-12 20:34 UTC, mrshu commented on docs/end-of-2022-challenge.md
> +* All the robots are able to react to the ball and play a game (you have to create a simple program for them)
```suggestion
* All the robots are able to react to the ball and play a game (you need to create a simple program for them)
```

2022-10-12 20:34 UTC, mrshu commented on docs/end-of-2022-challenge.md
> +out their [guide](https://cyberbotics.com/doc/guide/menu) and
@Adman Adding these links is great but it feels like they are rather general. Would there be a docs link that would directly describe how one can create/change objects via/in Webots?

2022-10-12 20:34 UTC, mrshu commented on docs/end-of-2022-challenge.md
> +**Submit via [https://forms.gle/YWAPFikxqLnAdVXTA](https://forms.gle/YWAPFikxqLnAdVXTA)**
@Adman I really think it would make sense to simply say "Send a PR against https://github.com/RoboCupJuniorTC/rcj-soccersim/ and add a tag `2022-challenge`" or something like that

2022-10-13 17:44 UTC, Adman commented on docs/end-of-2022-challenge.md
> +noticed that many of the robots use omiwheled way of moving on the field,
Yeah, changed

2022-10-13 17:45 UTC, Adman commented on docs/end-of-2022-challenge.md
> +**Submit via [https://forms.gle/YWAPFikxqLnAdVXTA](https://forms.gle/YWAPFikxqLnAdVXTA)**
Well yeah, let' see how that goes

2022-10-13 17:48 UTC, Adman commented on docs/end-of-2022-challenge.md
> +out their [guide](https://cyberbotics.com/doc/guide/menu) and
I haven't found something that would focus on modeling 3D objects there. The information is spread around that webpage.

2022-10-15 15:45 UTC, mrshu approved these changes
@Adman thanks for incorporating all the changes!

2022-10-18 15:30 UTC, merged